version: "3"

services:
    front:
      build:
        context: "./nginx"
      image: homepage
      ports:
          - "80:80"
      container_name: homepage-nginx
      restart: unless-stopped
      volumes:
          - ./configs/frontend:/usr/share/nginx/html/config
      expose:
        - "80"
    node:  
      build:
        context: "./node_server"
      image: homepage-node
      container_name: homepage-node
      restart: unless-stopped
      expose:
        - "6969"
    redis:
      container_name: homepage-redis
      image: 'redis:latest'
      ports:
          - "6379:6379"
      expose:
        - "6379"
      environment: 
        - REDIS_PASSWORD=qwerty123
      depends_on:
        - front